version: '3.8'

services:
  emotion-bot:
    build: .

    container_name: emotion-duel-bot

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - bot_data:/app/data

volumes:
  bot_data: